USE usdanlsr28;

ALTER TABLE FOOD_DES 
	ADD CONSTRAINT FOOD_DES_FK FOREIGN KEY(FdGrp_Cd) REFERENCES FD_GROUP(FdGrp_Cd);

ALTER TABLE NUT_DATA 
	ADD CONSTRAINT NUT_DATA_NDBNO_FK FOREIGN KEY(NDB_No) REFERENCES FOOD_DES(NDB_No),
	ADD CONSTRAINT NUT_DATA_NUTDEF_FK FOREIGN KEY(Nutr_No) REFERENCES NUTR_DEF(Nutr_No);

ALTER TABLE WEIGHT 
	ADD CONSTRAINT WEIGHT_NDBNO_FK FOREIGN KEY(NDB_No) REFERENCES FOOD_DES(NDB_No);

ALTER TABLE LANGUAL 
	ADD CONSTRAINT LANGUAL_FOOD_DES_FK FOREIGN KEY (NDB_No) REFERENCES FOOD_DES(NDB_No),
	ADD CONSTRAINT LANGUAL_LANGDESC_FK FOREIGN KEY (Factor_Code) REFERENCES LANGDESC(Factor_Code);

ALTER TABLE DATSRCLN 
	ADD CONSTRAINT DATSRCLN_NDB_FK FOREIGN KEY(NDB_No) REFERENCES FOOD_DES(NDB_No),
	ADD CONSTRAINT DATSRCLN_NUT_FK FOREIGN KEY(Nutr_No) REFERENCES NUTR_DEF(Nutr_No),
	ADD CONSTRAINT DATSRCLN_SRC_FK FOREIGN KEY(DataSrc_ID) REFERENCES DATA_SRC(DataSrc_ID);